#pragma once

#include <cppcoro/generator.hpp>
#include <cstdint>
#include <vector>
#include <concepts>
#include <ranges>

namespace ecgen {

    /**
     * @brief Ehrlich's algorithm for permutation generation
     * 
     * Generates all permutations using Ehrlich's algorithm,
     * which uses a more efficient in-place method than SJT.
     * 
     * @param n Length of permutation
     * @return Generator yielding permutations as vectors
     */
    auto ehr_gen(int n) -> cppcoro::generator<std::vector<int>>;

    /**
     * @brief Apply Ehrlich's algorithm to a container
     * 
     * Generates permutations in-place using Ehrlich's algorithm.
     * 
     * @tparam Container Type of container
     * @param container The container to permute
     * @return Generator yielding reference to container after each permutation
     */
    template<typename Container>
    auto ehr_apply(Container& container) -> cppcoro::generator<Container&> {
        int num = std::size(container);
        std::vector<int> c(num, 0);
        std::vector<int> o(num, 1);
        
        co_yield container;
        
        while (true) {
            int pos = num - 1;
            int sum = 0;
            
            // Determine next permutation
            int quot = c[pos] + o[pos];
            while (quot < 0 || quot == pos + 1) {
                if (quot == pos + 1) {
                    if (pos == 0) {
                        co_return; // All permutations generated
                    }
                    sum += 1;
                }
                o[pos] = -o[pos];
                pos -= 1;
                quot = c[pos] + o[pos];
            }
            
            // Swap elements
            std::swap(container[pos - c[pos] + sum], container[pos - quot + sum]);
            c[pos] = quot;
            
            co_yield container;
        }
    }

    /**
     * @brief Number of permutations generated by Ehrlich's algorithm
     * 
     * @param n Length of permutation
     * @return Number of permutations (n!)
     */
    constexpr auto ehr_count(int num) -> std::size_t {
        std::size_t result = 1;
        for (int idx = 2; idx <= num; ++idx) {
            result *= idx;
        }
        return result;
    }

} // namespace ecgen