#pragma once

#include <cppcoro/generator.hpp>
#include <cstdint>
#include <vector>
#include <concepts>
#include <ranges>

namespace ecgen {

    /**
     * @brief Ehrlich's algorithm for permutation generation
     * 
     * Generates all permutations using Ehrlich's algorithm,
     * which uses a more efficient in-place method than SJT.
     * 
     * @param n Length of permutation
     * @return Generator yielding permutations as vectors
     */
    auto ehr_gen(int n) -> cppcoro::generator<std::vector<int>>;

    /**
     * @brief Apply Ehrlich's algorithm to a container
     * 
     * Generates permutations in-place using Ehrlich's algorithm.
     * 
     * @tparam Container Type of container
     * @param container The container to permute
     * @return Generator yielding reference to container after each permutation
     */
    template<typename Container>
    auto ehr_apply(Container& container) -> cppcoro::generator<Container&> {
        int n = std::size(container);
        std::vector<int> c(n, 0);
        std::vector<int> o(n, 1);
        
        co_yield container;
        
        while (true) {
            int j = n - 1;
            int s = 0;
            
            // Determine next permutation
            int q = c[j] + o[j];
            while (q < 0 || q == j + 1) {
                if (q == j + 1) {
                    if (j == 0) {
                        co_return; // All permutations generated
                    }
                    s += 1;
                }
                o[j] = -o[j];
                j -= 1;
                q = c[j] + o[j];
            }
            
            // Swap elements
            std::swap(container[j - c[j] + s], container[j - q + s]);
            c[j] = q;
            
            co_yield container;
        }
    }

    /**
     * @brief Number of permutations generated by Ehrlich's algorithm
     * 
     * @param n Length of permutation
     * @return Number of permutations (n!)
     */
    constexpr auto ehr_count(int n) -> std::size_t {
        std::size_t result = 1;
        for (int i = 2; i <= n; ++i) {
            result *= i;
        }
        return result;
    }

} // namespace ecgen